image: sesame-ubuntu-16.04:1.0

variables:
  SHEEP_CI_RUNNER_IP: "17.18.99.1"
  SYS_TEST_FILE: "${CI_PROJECT_DIR}/tests/integration_test/system_test.yml"

stages:
  - test-unit
  - code-style
  - test-integ

unit-test:
  stage: test-unit
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/unit_tests/run
  tags:
    - unit-tests

code-formatting:
  stage: code-style
  script:
    - cd ${CI_PROJECT_DIR}
    - shfmt -sr -i 0 -d sheep tests/unit_tests/run tests/integration_test/run
  tags:
    - unit-tests

ubuntu16_04_qcow2_uefi_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: ubuntu16_04_uefi_CID_leopard.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration

centos7_qcow2_uefi_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: centOS7_uefi_CID_leopard.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration

debian9_qcow2_uefi_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: debian9_legacy_CID_leopard.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration

opensuse15_1_qcow2_uefi_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: openSUSE15_1_uefi_CID_leopard.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration

ubuntu16_04_qcow2_legacy_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: ubuntu16_04_legacy_CID_winterfell.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,115200n8 iomem=relaxed ethdevice=enp12s0 module_blacklist=mei,mei_me sheep.log.level=DEBUG sheep.delay=10
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration-legacy

centos7_qcow2_legacy_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: centOS7_legacy_CID_winterfell.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,115200n8 iomem=relaxed ethdevice=enp12s0 module_blacklist=mei,mei_me
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration-legacy

debian9_qcow2_legacy_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: debian9_legacy_CID_winterfell.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,115200n8 iomem=relaxed ethdevice=enp12s0 module_blacklist=mei,mei_me
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration-legacy

opensuse15_1_qcow2_legacy_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: openSUSE15_1_legacy_CID_winterfell.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,115200n8 iomem=relaxed ethdevice=enp12s0 module_blacklist=mei,mei_me
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration-legacy

ubuntu16_04_qcow2_legacy_boot_CIE:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: ubuntu16_04_legacy_CIE_winterfell.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,115200n8 iomem=relaxed ethdevice=enp12s0 module_blacklist=mei,mei_me
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration-legacy

centos7_qcow2_legacy_boot_CIE:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: centOS7_legacy_CIE_winterfell.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,115200n8 iomem=relaxed ethdevice=enp12s0 module_blacklist=mei,mei_me
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration-legacy

debian9_qcow2_legacy_boot_CIE:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: debian9_legacy_CIE_winterfell.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,115200n8 iomem=relaxed ethdevice=enp12s0 module_blacklist=mei,mei_me
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration-legacy

opensuse15_1_qcow2_legacy_boot_CIE:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: openSUSE15_1_legacy_CIE_winterfell.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,115200n8 iomem=relaxed ethdevice=enp12s0 module_blacklist=mei,mei_me
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration-legacy

ubuntu16_04_uefi_leopard__boot_order_once:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: ubuntu16_04_uefi_leopard__boot_order_once.yml
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - "*.cast"
  tags:
    - integration
